name: CI

on:
  push:
    branches: [main]
    tags: ["*"]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
      - package.json
      - tree-sitter.json
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
      - package.json
      - tree-sitter.json

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@eeb902ac2f1be576edc296309872cf476a209b7f # v2
      - name: Run parser tests
        run: tree-sitter test
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: lts/*
      - name: Test Node bindings
        run: npm install && node --test bindings/node/*_test.js

  package:
    name: Build package
    needs: test
    uses: ./.github/workflows/package-npm.yml
    # secrets:
    #   NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
