name: Test parser

on:
  workflow_call:

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@eeb902ac2f1be576edc296309872cf476a209b7f # v2
      - name: Run parser tests
        run: tree-sitter test
